### PR TITLE
Add some links

### PR DESCRIPTION
**Pull request by jamiebuilds**
Still working on this, had to take off for a bit

### CODE REVIEW

**Comment by dustinspecker** [comment]
Thank you! This is amazing!

**Comment by yangshun** [comment]
@dustinspecker @thejameskyle How's this PR coming along? I have some time and wouldn't mind resolving the conflicts and updating with content so that it can be merged. There seems to be many useful content in this PR (:

**Comment by sibelius** [comment]
@yangshun can you merge this?

**Comment by yangshun** [comment]
Sorry I have no write permissions. You'll have to ping @dustinspecker

**Comment by sibelius** [comment]
@dustinspecker can you merge this

there are a lot of great links here

**Comment by dustinspecker** [comment]
Rebased and pushed onto master.

Sorry for the delay and thank you for all of the great links!

**Pull request closed without merging**
